---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    image: archlinux:latest
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    MOLECULE_NO_LOG: true
    MOLECULE_MODE: true
  # options:
  #   vvv: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - destroy
