- name: Check if bat is installed
  stat:
    path: '~/.cargo/bin/bat'
  register: bat

- name: make sure bat is installed
  shell: source $HOME/.cargo/env && cargo install bat
  when: bat.stat.exists == False
  ignore_errors: yes

- name: Check if exa is installed
  stat:
    path: '~/.cargo/bin/exa'
  register: exa

- name: make sure exa is installed
  shell: source $HOME/.cargo/env && cargo install exa
  when: exa.stat.exists == False
  ignore_errors: yes

- name: Check if ytop is installed
  stat:
    path: '~/.cargo/bin/ytop'
  register: ytop

- name: make sure ytop is installed
  shell: source $HOME/.cargo/env && cargo install ytop
  when: ytop.stat.exists == False
  ignore_errors: yes

