- include_tasks: tpl.yml
  with_items:
    - cargo-update
    - lfs
    - ytop
    - bottom
    - exa
    - lsd
    - natls
    - fd-find
    - hyperfine
    - topgrade
    - bat

- name: Check if ox is installed
  stat:
    path: "~/.cargo/bin/ox"
  register: ox

- name: make sure ox is installed
  shell: . $HOME/.cargo/env && cargo install --git https://github.com/curlpipe/ox
  when: not ox.stat.exists
  ignore_errors: yes
  changed_when: false
