- include_tasks: tpl.yml
  with_items:
    - bat
    - exa
    - ytop
    - lfs

- name: Check if ox is installed
  stat:
    path: '~/.cargo/bin/ox'
  register: ox

- name: make sure ox is installed
  shell: . $HOME/.cargo/env && cargo install --git https://github.com/curlpipe/ox
  when: not ox.stat.exists
  ignore_errors: yes

- name: Check if nat is installed
  stat:
    path: '~/.cargo/bin/nat'
  register: nat

- name: make sure nat is installed
  when: not nat.stat.exists
  ignore_errors: yes
  block:
    - git:
        repo: https://github.com/willdoescode/nat.git
        dest: /tmp/nat
    - shell: . $HOME/.cargo/env && cargo install --path /tmp/nat
