- include_tasks: tpl.yml
  with_items:
    - bat
    - exa
    - ytop
    - lfs

- name: Check if ox is installed
  stat:
    path: '~/.cargo/bin/ox'
  register: ox

- name: make sure ox is installed
  shell: . $HOME/.cargo/env && cargo install --git https://github.com/curlpipe/ox
  when: ox.stat.exists == False
  ignore_errors: yes
  changed_when: false
