- name: check if pacman-mirrors exists
  shell: command -v pacman-mirrors > /dev/null 2>&1
  ignore_errors: yes
  no_log: yes
  register: pacman_mirrors

- name: make sure pacman branch is set to unstable
  block:
    - name: Gather pacman branch facts
      command: pacman-mirrors -G
      register: pacman_branch

    - set_fact: pacman_branch={{ pacman_branch.stdout }}

    - name: Set pacman branch to unstable and rebuild mirrors
      shell: |
        pacman-mirrors --api --set-branch unstable
        pacman-mirrors --fasttrack 5
      when: pacman_branch != "unstable"
      become: yes
  when: not ansible_check_mode and not pacman_mirrors.failed

- name: make sure yay (aur package manager) is installed
  aur:
    name: yay
    use: makepkg
    skip_installed: yes
