- name: make sure pacman branch is set to unstable
  block:
    - name: Gather pacman branch facts
      command: pacman-mirrors -G
      register: pacman_branch

    - set_fact: pacman_branch={{ pacman_branch.stdout }}

    - name: Set pacman branch to unstable and rebuild mirrors
      shell: |
        pacman-mirrors --api -S unstable
        pacman-mirrors --fasttrack 5
        pacman -Syu
      when: pacman_branch != "unstable"
      become: yes
  when: not ansible_check_mode

- name: make sure yay (aur package manager) is installed
  aur:
    name: yay
    use: makepkg
    skip_installed: yes
