- name: Gather pacman branch facts
  shell: pacman-mirrors -G
  register: pacman_branch

- set_fact: pacman_branch={{ pacman_branch.stdout }}

- name: Set pacman branch to unstable and rebuild mirrors
  shell: |
    pacman-mirrors --api --set-branch unstable
    pacman-mirrors --fasttrack 5
  when: pacman_branch != "unstable"
