- name: "Install yay"
  package:
    name: yay
    state: present
  become: yes
  ignore_errors: yes
  register: yay

- name: "Install yay with makepkg"
  block:
    - git:
        repo: https://aur.archlinux.org/yay.git
        dest: yay
    - shell: cd yay && makepkg -sic
  when: yay.failed and not yay.changed
  ignore_errors: yes
