- include_tasks: "{{ ansible_os_family }}.yml"

- name: Create alacritty folder in .config
  file:
    path: ~/.config/alacritty/
    state: directory

- name: symlink files
  file:
    src: "{{ ansible_env.PWD }}/roles/terminal/alacritty/files/{{ item }}"
    path: "~/.config/alacritty/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - alacritty.yml