- name: Setup local environment
  hosts: localhost
  roles:
    - system/pkmng
    - editor/vim
    - editor/vs_code
    - editor/sublime
    - git
    - font
    - system/zip
    - terminal/alacritty
    - terminal/tmux
    - terminal/yakuake
    - terminal/taskwarrior
    - terminal/starship
    - shell/fish
    - docker
    - programming/php
    - programming/rust
    - programming/rust/cargo
    - programming/rust/tools
    - programming/jetbrains
    - programming/workspace
    - profanity
    - credentials
    - browser/brave
    - browser/chrome
    - postman
    - system/default
