- name: Setup local environment
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    use_unstable_pacman_branch: yes
    use_fish: yes
    use_zsh: no
    use_starship_prompt: yes
    on_wsl: no
  roles:
    - system/pacman
    - system/zip
    - editor/vim
    - editor/vs_code
    - editor/sublime
    - git
    - font
    - shell/fish
    - shell/starship
    - terminal/alacritty
    - terminal/zellij
    - terminal/tmux
    - terminal/yakuake
    - docker
    - ansible
    - ansible/molecule
    - programming/rust
    - programming/rust/cargo
    - programming/rust/tools
    - browser/brave
    - browser/firefox
    - zola
    - aws/cli
    - system/default
