- name: Setup local environment
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    use_fish: no
    use_zsh: yes
    use_starship_prompt: yes
    dist_ubuntu: xenial
    dist_debian: bullseye
    on_wsl: yes
  roles:
    - system/apt
    - system/zip
    - editor/vim
    - curl
    - git
    - font
    - shell/zsh
    - shell/starship
    - terminal/zellij
    - terminal/tmux
    - docker
    - ansible
    - ansible/molecule
    - programming/python
    - programming/rust
    - programming/rust/cargo
    - programming/rust/tools
    - system/debian-wsl
    - aws/terraform
    - aws/cli
