- name: Setup local environment
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    use_fish: no
    use_zsh: yes
    use_starship_prompt: yes
  roles:
    - system/zip
    - editor/vim
    - git
    - shell/zsh
    - shell/starship
    - terminal/tmux
    - terminal/taskwarrior
    - docker
    - programming/rust
    - programming/rust/cargo
    - programming/rust/tools
