- name: make sure php is installed
  package:
    name: php
    state: present
  become: yes

- name: make sure composer is installed
  package:
    name: composer
    state: present
  become: yes

- name: make sure php-pear for pecl is installed
  yay:
    name: php-pear
    state: present