- name: make sure php is installed
  package:
    name: php
    state: latest
  become: yes

- name: make sure composer is installed
  package:
    name: composer
    state: latest
  become: yes

- name: install extensions
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-gd
    - php-sqlite
  become: yes
