- name: make sure pacman branch is set to unstable
  block:
    - name: Gather pacman branch facts
      command: pacman-mirrors -G
      register: pacman_branch

    - set_fact: pacman_branch={{ pacman_branch.stdout }}

    - name: Set pacman branch to unstable
      shell: |
        pacman-mirrors --api -S unstable
        pacman-mirrors --fasttrack 5
      when: pacman_branch != "unstable"

    - name: Rebuild mirrors
      shell: yes | pacman -Syu
      become: yes
      when: pacman_branch != "unstable"
