- name: Check if sublime-text is imported
  lineinfile:
    path: /etc/pacman.conf
    line: '[sublime-text]'
    state: absent
  check_mode: yes
  changed_when: false
  register: sublime

- name: makre sure glibc is installed
  package:
    name: glibc
    state: present
  become: yes

- name: init pacman-key
  command: pacman-key --init
  become: yes
  changed_when: false
  ignore_errors: yes

- name: download sublime-text gpg key
  shell: curl -O https://download.sublimetext.com/sublimehq-pub.gpg
  args:
    warn: no
  when: not sublime.found

- name: import sublime-text gpg key
  shell: |
    pacman-key --add sublimehq-pub.gpg
    pacman-key --lsign-key 8A8F901A
  become: yes
  when: not sublime.found

- name: remove sublime-text gpg.key
  file:
    path: sublimehq-pub.gpg
    state: absent
  when: not sublime.found

- name: add sublime-text server
  shell: echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
  become: yes
  when: not sublime.found

- name: make sure pacman branch is set to unstable
  block:
    - name: Gather pacman branch facts
      command: pacman-mirrors -G
      register: pacman_branch
      changed_when: false

    - name: Set pacman branch to unstable
      shell: |
        pacman-mirrors --api -S unstable
        pacman-mirrors --fasttrack 5
  when: use_unstable_pacman_branch and pacman_branch.stdout != "unstable"

- name: Rebuild mirrors & update packages
  pacman:
    update_cache: yes
    upgrade: yes
  changed_when: false
  become: yes
  when: not use_unstable_pacman_branch
