- name: init keys
  command: pacman-key --init
  changed_when: false
  become: yes

- name: Check if sublime-text is imported
  lineinfile:
    path: /etc/pacman.conf
    line: '[sublime-text]'
    state: absent
  check_mode: yes
  changed_when: false
  register: sublime

- name: download sublime-text gpg key
  shell: curl -O https://download.sublimetext.com/sublimehq-pub.gpg
  when: not sublime.found

- name: import sublime-text gpg key
  shell: |
    pacman-key --add sublimehq-pub.gpg
    pacman-key --lsign-key 8A8F901A
  become: yes
  when: not sublime.found

- name: remove sublime-text gpg.key
  file:
    path: sublimehq-pub.gpg
    state: absent
  when: not sublime.found

- name: add sublime-text server
  shell: echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
  become: yes
  when: not sublime.found

- name: make sure pacman branch is set to unstable
  block:
    - name: Gather pacman branch facts
      changed_when: false
      ignore_errors: yes
      command: pacman-mirrors -G
      register: pacman_branch

    - name: Set pacman branch to unstable
      changed_when: false
      ignore_errors: yes
      shell: |
        pacman-mirrors --api -S unstable
        pacman-mirrors --fasttrack 5
      when: pacman_branch.stdout != "unstable"
  when: not ansible_check_mode and use_unstable_pacman_branch

- name: Update package cache
  changed_when: false
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes
