- name: Check if cargo-edit is installed
  stat:
    path: '~/.cargo/bin/cargo-add'
  register: cargo_edit

- name: 'make sure cargo-edit is installed'
  shell: . $HOME/.cargo/env && cargo install cargo-add
  when: not cargo_edit.stat.exists

- name: Check if cargo-watch is installed
  stat:
    path: '~/.cargo/bin/cargo-watch'
  register: cargo_watch

- name: make sure cargo-watch is installed
  shell: . $HOME/.cargo/env && cargo install cargo-watch
  when: not cargo_watch.stat.exists
