- name: Check if cargo-edit is installed
  stat:
    path: '~/.cargo/bin/cargo-edit'
  register: cargo_edit

- name: 'make sure cargo-edit is installed'
  shell: source $HOME/.cargo/env && cargo install cargo-edit
  when: cargo_edit.stat.exists == False

- name: Check if cargo-watch is installed
  stat:
    path: '~/.cargo/bin/cargo-watch'
  register: cargo_watch

- name: make sure cargo-watch is installed
  shell: source $HOME/.cargo/env && cargo install cargo-watch
  when: cargo_watch.stat.exists == False
