- git:
    repo: https://github.com/Dgame/{{ item }}
    dest: ~/workspace/dgame/{{ item }}
  with_items:
    - workspace
    - blog

- name: create terminal bookmarks
  shell: "cd ~/workspace/dgame/{{ item }} && to add"
  args:
    executable: "/usr/bin/fish"
  with_items:
    - workspace
    - blog
