- name: Check if workspace is installed
  stat:
    path: '~/.cargo/bin/workspace'
  register: workspace

- name: 'make sure workspace is installed'
  shell: source $HOME/.cargo/env && cargo install --git https://github.com/Dgame/workspace.git --force
  when: workspace.stat.exists == False

- name: 'Checking workspace folders'
  stat:
    path: "{{item}}"
  register: workspace
  with_items:
    - ["~/workspace/dgame"]

- name: 'Creating workspace folders'
  file:
    path: "{{item.item}}"
    state: directory
  when: item.stat.exists == False
  with_items:
    - "{{workspace.results}}"

- name: 'symlink files'
  file:
    src: "{{ ansible_env.PWD }}/roles/programming/workspace/files/{{ item }}"
    path: "~/workspace/{{ item }}"
    state: link
    follow: false
    force: yes
  with_items:
    - ["dgame/workspace.toml"]

- name: 'sync workspace'
  shell: 'source $HOME/.cargo/env && workspace sync'
  args:
    chdir: '{{ item.stat.path }}'
  when: item.stat.exists
  with_items:
    - "{{workspace.results}}"
