- name: install sublime-text dependencies
  package:
      name: '{{ item }}'
      state: present
  loop:
    - freetype2
    - mesa

- name: make sure sublime-text is installed
  package:
    name: sublime-text
    state: present
