- name: check if jetbrains-toolbox was downloaded
  stat:
    path: ~/.workspace/jetbrains-toolbox
  register: jetbrains_toolbox

- name: download jetbrains-toolbox
  git:
    repo: https://aur.archlinux.org/jetbrains-toolbox.git
    dest: ~/.workspace/jetbrains-toolbox
  when: jetbrains_toolbox.stat.exists == False

- name: check if jetbrains-toolbox was downloaded
  stat:
    path: ~/.workspace/jetbrains-toolbox
  register: jetbrains_toolbox

- name: build jetbrains-toolbox
  command: makepkg -sic --noconfirm --skippgpcheck
  args:
    chdir: ~/.workspace/jetbrains-toolbox
  when: jetbrains_toolbox.stat.exists
