- name: setup vagrant
  package:
    name:
      - vagrant
      - virtualbox
      - "linux{{ linux_kernel_version }}-virtualbox-host-modules"
  become: yes

- name: reload virtualbox
  command: vboxreload
  become: yes
