---
- name: Prepare
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: setup pacman
      command: pacman -Sy

    - name: install sudo
      package:
        name: sudo
        state: present
