- name: Check if workspace is installed
  stat:
    path: '~/.cargo/bin/workspace'
  register: workspace

- name: 'Install workspace'
  shell: source $HOME/.cargo/env && cargo install --git https://github.com/Dgame/workspace.git --force
  when: workspace.stat.exists == False

- name: 'Checking workspace folders'
  stat:
    path: "{{item}}"
  register: workspace
  with_items:
    - ["~/workspace/dgame"]

- name: 'Creating workspace folders'
  file:
    path: "{{item.item}}"
    state: directory
  when: item.stat.exists == False
  with_items:
    - "{{workspace.results}}"

- name: 'symlink files'
  file:
    src: "{{ ansible_env.PWD }}/roles/workspace/files/{{ item }}"
    path: "~/workspace/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - dgame/workspace.toml
  
- name: 'sync and build dgame/workspace.toml'
  shell: source $HOME/.cargo/env && workspace sync && workspace build
  args:
    chdir: ~/workspace/dgame
