- name: set default applications
  file:
    src: "{{ ansible_env.PWD }}/roles/system/default/files/{{ item }}"
    path: "~/.config/{{ item }}"
    state: link
    follow: no
    force: yes
  loop:
    - mimeapps.list
