- name: make sure linux-headers are installed
  package:
    name: "linux{{ linux_kernel_version }}-headers"
    state: present
  become: yes
  register: linux_headers
  ignore_errors: yes

- name: make sure linux-headers are installed
  package:
    name: linux-headers
    state: present
  become: yes
  when: not linux_headers.changed and linux_headers.msg.find('failed to install') != -1
  ignore_errors: yes
