- name: Check if starship is installed
  stat:
    path: '~/.cargo/bin/starship'
  register: starship
  when: use_starship_prompt

- name: make sure starship is installed
  shell: . $HOME/.cargo/env && cargo install starship
  when: use_starship_prompt and starship.stat.exists == False
  ignore_errors: yes

- name: Add starship to ~/.config/fish/config.fish
  lineinfile:
    state: present
    path: ~/.config/fish/config.fish
    insertafter: EOF
    line: starship init fish | source
  when: use_fish and use_starship_prompt

- name: Add starship to ~/.zshrc
  lineinfile:
    state: present
    path: ~/.zshrc
    insertafter: EOF
    line: eval "$(starship init zsh)"
  when: not use_fish and use_starship_prompt

- name: Create ~/.config folder
  file:
    path: ~/.config
    state: directory

- name: symlink starship.toml
  when: use_starship_prompt
  file:
    src: "files/starship.toml"
    path: ~/.config/starship.toml
    state: link
    follow: false
    force: yes
    mode: 0644
