- name: Check if starship is installed
  stat:
    path: '~/.cargo/bin/starship'
  register: starship
  when: use_starship_prompt

- name: make sure starship is installed
  shell: . $HOME/.cargo/env && cargo install starship
  when: use_starship_prompt and not starship.stat.exists
  ignore_errors: yes

- name: Install pamac
  package:
    name: pamac
    state: present
  become: yes
  ignore_errors: yes
  register: pamac
  when: not on_wsl and ansible_os_family == "Archlinux"

- name: Install Nerd-Fonts
  command: pamac build nerd-fonts-complete --no-confirm
  ignore_errors: yes
  changed_when: false
  when: ansible_os_family == "Archlinux" and pamac is succeeded

- name: Create ~/.config folder
  file:
    path: ~/.config
    state: directory

- name: symlink starship.toml
  when: use_starship_prompt
  file:
    src: "{{ ansible_env.PWD }}/roles/shell/starship/files/starship.toml"
    path: ~/.config/starship.toml
    state: link
    follow: false
    force: yes
    mode: 0644

- name: Add starship to ~/.config/fish/config.fish
  changed_when: false
  lineinfile:
    state: present
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    insertafter: EOF
    line: starship init fish | source
  when: use_fish and use_starship_prompt

- name: Add starship to ~/.zshrc
  changed_when: false
  lineinfile:
    state: present
    path: "{{ ansible_env.HOME }}/.zshrc"
    insertafter: EOF
    line: eval "$(starship init zsh)"
  when: use_zsh and use_starship_prompt

- name: Update starship
  shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
  become: yes
  ignore_errors: yes
  changed_when: false
