- name: Check if starship is installed
  stat:
    path: '~/.cargo/bin/starship'
  register: starship
  when: use_starship_prompt

- name: make sure starship is installed
  shell: source $HOME/.cargo/env && cargo install starship
  when: use_starship_prompt and starship.stat.exists == False
  ignore_errors: yes

- name: Add starship to ~/.config/fish/config.fish
  lineinfile:
    state: present
    path: ~/.config/fish/config.fish
    insertafter: EOF
    line: starship init fish | source
  when: use_starship_prompt

- name: symlink starship.toml
  when: use_starship_prompt
  file:
    src: "files/{{ item }}"
    path: "~/.config/{{ item }}"
    state: link
    follow: no
    force: yes
  loop:
    - starship.toml
