- include_tasks: "{{ ansible_os_family }}.yml"

- block:
    - name: Create fish folder in ~/.config
      file:
        path: ~/.config/fish/
        state: directory

    - name: copy dotfiles
      copy:
        src: "files/{{ item }}"
        dest: "~/.config/fish/{{ item }}"
        force: no
      loop:
        - config.fish
        - fish_variables

    - name: Check if fisher is installed
      stat:
        path: '~/.config/fisher'
      register: fisher

    - name: "make sure fisher is installed"
      changed_when: false
      command: "curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish"
      args:
        warn: false
      when: fisher.stat.exists == False

    - name: Check if matchai/spacefish (prompt) is installed
      stat:
        path: '~/.config/fisher/github.com/matchai/spacefish'
      register: spacefish
      when: not use_starship_prompt

    - name: "make sure matchai/spacefish (prompt) is installed"
      changed_when: false
      shell: "fisher add matchai/spacefish"
      args:
        executable: "/usr/bin/fish"
      when: not use_starship_prompt and spacefish.stat.exists == False

    - name: Check if joehillen/to-fish (bookmarks) is installed
      stat:
        path: '~/.config/fisher/github.com/joehillen/to-fish'
      register: to_fish

    - name: "make sure joehillen/to-fish (bookmarks) is installed"
      changed_when: false
      shell: "fisher add joehillen/to-fish"
      args:
        executable: "/usr/bin/fish"
      when: to_fish.stat.exists == False

    - name: Add fish to /etc/shells
      changed_when: false
      command: grep -q "/usr/bin/fish" /etc/shells || echo /usr/bin/fish | tee -a /etc/shells
      become: yes

    - name: Set fish as default shell
      changed_when: false
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/fish
      become: yes
  when: use_fish
