- name: Create .credentials folder
  file:
    path: ~/.credentials
    state: directory

- name: symlink files
  file:
    src: "files/{{ item }}"
    path: "~/.credentials/{{ item }}"
    state: link
    follow: no
    force: yes
  loop:
    - imp.kdbx

- include_tasks: "{{ ansible_os_family }}.yml"
