---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: manjaro
    image: manjarolinux/base
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ANSIBLE_LIBRARY: ../../library
  # options:
    # vvv: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - destroy
