- name: Install gzip
  package:
    name: gzip
    state: latest
  become: yes

- name: Install zip
  package:
    name: zip
    state: latest
  become: yes

- name: Install unzip
  package:
    name: unzip
    state: latest
  become: yes
