- name: make sure git is installed
  package:
    name: git
    state: present
  become: yes

- name: make sure github-cli is installed
  package:
    name: gitub-cli
    state: present
  become: yes
