- include_tasks: "{{ ansible_os_family }}.yml"

- name: copy gitconfig
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/.gitconfig"
    path: ~/.gitconfig
    state: link
    follow: false
    force: yes
    mode: 0644
