- name: Install WSL utilities
  block:
    - name: Copy .wslconfig
      copy:
        src: "{{ ansible_env.PWD }}/roles/system/debian-wsl/files/{{ item }}"
        dest: "{{ user_profile.stdout }}/{{ item }}"
        follow: no
        force: yes
      loop:
        - .wslconfig
      ignore_errors: yes
      when: user_profile.rc | default(-1) == 0
  when: ansible_distribution == "Ubuntu"