- include_tasks: "{{ ansible_os_family }}.yml"

- name: make sure curl is installed
  package:
    name: curl
    state: latest
  become: yes

- name: make sure tree is installed
  package:
    name: tree
    state: latest
  become: yes

- name: make sure jq is installed
  package:
    name: jq
    state: latest
  become: yes