- set_fact:
    molecule_mode: "{{ lookup('env', 'MOLECULE_MODE')|default(false)|bool }}"

- set_fact:
    validate_certs: "{{ False if (molecule_mode) else True }}"

- name: Install aws-cli
  block:
    - name: Download aws-cli v2 installer
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
        creates: /tmp/aws
        mode: 0755
        validate_certs: "{{ validate_certs }}"

    - name: Run the installer.
      command:
        cmd: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
        creates: /usr/local/bin/aws
      become: true