- include_tasks: "{{ ansible_os_family }}.yml"

- name: install vs-code extensions
  shell: |
    code --install-extension azemoh.one-monokai
    code --install-extension bbenoist.vagrant
    code --install-extension bmalehorn.vscode-fish
    code --install-extension bmewburn.vscode-intelephense-client
    code --install-extension bungcip.better-toml
    code --install-extension kokororin.vscode-phpfmt
    code --install-extension rust-lang.rust
    code --install-extension TabNine.tabnine-vscode
    code --install-extension vscoss.vscode-ansible
    code --install-extension yzhang.markdown-all-in-one
  ignore_errors: yes
  register: vs_code

- name: symlink vs-code extensions
  block:
    - name: copy vs-code settings
      file:
        src: "{{ ansible_env.PWD }}/roles/editor/vs_code/files/{{ item }}"
        path: "~/.config/Code - OSS/User/{{ item }}"
        state: link
        follow: false
        force: yes
      loop:
        - settings.json

    - name: make sure CachedExtensions exists
      file:
        path: ~/.config/Code - OSS/CachedExtensions
        state: directory

    - name: copy vs-code extension
      copy:
        src: "{{ ansible_env.PWD }}/roles/editor/vs_code/files/{{ item }}"
        dest: "~/.config/Code - OSS/CachedExtensions/{{ item }}"
        force: no
      loop:
        - user
  when: not vs_code.failed
