- include_tasks: "{{ ansible_os_family }}.yml"

- name: install vs-code extensions
  shell: 'code --install-extension {{ item }}'
  ignore_errors: yes
  register: vs_code
  changed_when: false
  with_items:
    - 2gua.rainbow-brackets
    - azemoh.one-monokai
    - bbenoist.vagrant
    - bmalehorn.vscode-fish
    - bmewburn.vscode-intelephense-client
    - bungcip.better-toml
    - Gruntfuggly.todo-tree
    - kokororin.vscode-phpfmt
    - matklad.rust-analyzer
    - mhutchie.git-graph
    - rust-lang.rust
    - samverschueren.final-newline
    - serayuzgur.crates
    - TabNine.tabnine-vscode
    - vadimcn.vscode-lldb
    - vscoss.vscode-ansible
    - waderyan.gitblame
    - yzhang.markdown-all-in-one

- name: symlink vs-code extensions
  block:
    - name: copy vs-code settings
      changed_when: false
      file:
        src: "files/{{ item }}"
        path: "~/.config/Code - OSS/User/{{ item }}"
        state: link
        follow: no
        force: yes
      loop:
        - settings.json

    - name: make sure CachedExtensions exists
      file:
        path: ~/.config/Code - OSS/CachedExtensions
        state: directory

    - name: copy vs-code extension
      changed_when: false
      copy:
        src: "files/{{ item }}"
        dest: "~/.config/Code - OSS/CachedExtensions/{{ item }}"
        force: no
        mode: 0644
      loop:
        - user
