- name: make sure docker is installed
  package:
    name: docker
    state: present
  become: yes

- name: make sure docker-compose is installed
  package:
    name: docker-compose
    state: present
  become: yes
  ignore_errors: yes