- name: Update apt packages
  apt:
    update_cache: yes
  changed_when: false
  become: yes

- name: Install docker packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
  become: yes

- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
    mode: "0644"
  become: yes

- name: Install docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: latest
  become: yes
