- name: Update apt packages
  apt:
    update_cache: yes
  become: yes

- name: Install docker packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
  become: yes

- name: Add Dockers official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
    mode: "0644"
  become: yes

- name: Install docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: latest
  become: yes

- name: Update docker-compose
  block:
    - name: Check if /usr/local/bin/docker-compose exists
      stat:
        path: '/usr/local/bin/docker-compose'
      register: docker_compose
    - name: "Download docker-compose {{ docker_compose_version }}"
      uri:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
      when: not docker_compose.stat.exists
    - name: Check if /usr/bin/docker-compose exists
      stat:
        path: '/usr/bin/docker-compose'
      register: docker_compose_old
    - name: Rename old docker-compose
      copy:
        src: /usr/bin/docker-compose
        dest: /usr/bin/docker-compose-old
        remote_src: yes
      ignore_errors: yes
      when: docker_compose_old.stat.exists
    - name: Get docker-compose version
      shell: docker-compose --version
      changed_when: false
    - name: Delete old docker-compose
      file:
        state: absent
        path: /usr/bin/docker-compose
      when: docker_compose_old.stat.exists
    - name: Change chmod
      file:
        path: /usr/local/bin/docker-compose
        mode: +x
      when: not docker_compose.stat.exists
  ignore_errors: yes
  become: yes
