- name: Update apt packages
  apt:
    update_cache: yes
  changed_when: false
  become: yes

- name: Install docker packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
  become: yes

- name: Add Dockers official GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: yes

- name: Setup the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ dist_ubuntu }} stable"
    state: present
    update_cache: yes
    mode: "0644"
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Setup the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ dist_debian }} stable"
    state: present
    update_cache: yes
    mode: "0644"
  become: yes
  when: ansible_distribution == "Debian"

- name: Install docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Install docker-compose
  package:
    name: docker-compose
    state: latest
  become: yes
