- include_tasks: "{{ ansible_os_family }}.yml"

- name: Add Docker-Group
  group:
    name: docker
    state: present
  become: yes

- name: Add local User to Docker-Group
  user:
    append: yes
    groups: docker
    user: "{{ ansible_user_id }}"
  become: yes

- name: Ensure docker is enabled and running
  service:
    name: docker
    state: started
    enabled: yes
  become: true
  ignore_errors: yes # https://github.com/ansible/ansible/issues/71528
  when: ansible_distribution != "Ubuntu" # https://github.com/ansible/ansible/issues/71528#issuecomment-702178531
