- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  become: yes

- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  become: yes

- name: Update apt packages
  apt:
    update_cache: yes
  become: yes

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: yes

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes
  become: yes
