- name: make sure php is installed
  package:
    name: php
    state: present
  become: yes

- name: symlink php.ini
  file:
    src: "{{ ansible_env.PWD }}/roles/php/files/php.ini"
    path: /etc/php/php.ini
    state: link
    follow: false
    force: yes
  become: yes

- name: make sure composer is installed
  package:
    name: composer
    state: present
  become: yes

- name: install hirak/prestissimo for composer
  shell: composer global require hirak/prestissimo
  changed_when: false

- import_tasks: pecl.yml
