- include_tasks: "{{ ansible_os_family }}.yml"

- name: Check if tpm is installed
  stat:
    path: '~/.tmux/plugins/tpm'
  register: tpm

- name: make sure tpm is installed
  shell: "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
  changed_when: false
  when: tpm.stat.exists == False

- name: symlink .tmux.conf
  file:
    src: "{{ ansible_env.PWD }}/roles/terminal/tmux/files/.tmux.conf"
    path: ~/.tmux.conf
    state: link
    force: yes