- include_tasks: "{{ ansible_os_family }}.yml"

- name: symlink .tmux.conf
  file:
    src: "{{ ansible_env.PWD }}/roles/terminal/tmux/files/.tmux.conf"
    path: ~/.tmux.conf
    state: link
    force: yes
