- name: Check if rls is installed
  stat:
    path: '~/.cargo/bin/rls'
  register: rls

- name: 'make sure rls & rust-analysis is installed'
  shell: source $HOME/.cargo/env && rustup component add rls rust-analysis
  when: rls.stat.exists == False

- name: Check if racer is installed
  stat:
    path: '~/.cargo/bin/racer'
  register: racer

- name: 'make sure racer is installed'
  shell: source $HOME/.cargo/env && cargo +nightly install racer
  when: racer.stat.exists == False
