---
- name: make sure python3 is installed
  hosts: all
  gather_facts: false
  tasks:
    - name: run apt-get update and install python3
      raw: "{{ item }}"
      loop:
        - apt-get update
        - apt-get -y install python3

- name: Prepare
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install sudo
      package:
        name: sudo
        state: present
