name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_run:
    types:
      - completed
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FORKS: false
          MERGE_LABELS: "automerge,!work in progress,!wip"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 300000
          UPDATE_METHOD: "merge"
          UPDATE_RETRIES: 6
          UPDATE_RETRY_SLEEP: 300000
