name: merge master
on:
  pull_request:
    types:
      - synchronize
      - reopened
      - ready_for_review
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igordcsouza/github-action-get-branch-name@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: merge master
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'master'
          target: ${BRANCH_NAME}
