name: molecule
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - arch
          - manjaro
          - debian
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Prepare
        run:  |
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get -y install ansible
          python3 -m pip install --user "molecule"

      - name: Test playbook
        run: make -f ${{ matrix.scenario }}.mk test
